apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    # Puerto REST
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
    # Puerto gRPC
    - name: grpc
      port: 50056
      targetPort: 50056
      protocol: TCP
  type: ClusterIP
