apiVersion: v1
kind: Pod
metadata:
  name: inventary-pod
  labels:
    app: inventary
spec:
  containers:
    # --- FASTAPI CONTAINER ---
    - name: inventary-rest
      image: inventary-service:latest  # o tu imagen subida a Docker Hub / ECR
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      env:
        - name: MONGO_URI
          value: "mongodb+srv://Jcarvajal0810:Nutella_0810@sharedm0.d3q2w0n.mongodb.net/inventarydb?retryWrites=true&w=majority&appName=SharedM0"
        - name: PORT
          value: "8000"
        - name: RABBITMQ_HOST
          value: "rabbitmq"      # <-- coincide con el nombre del Service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "admin"
        - name: RABBITMQ_PASS
          value: "admin"  
      command: ["uvicorn"]
      args: ["src.main:app", "--host", "0.0.0.0", "--port", "8000"]
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"

    # --- GRPC CONTAINER ---
    - name: inventary-grpc
      image: inventary-service:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 50051
      command: ["python"]
      args: ["src/grpc_server.py"]
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"

---
# Servicio para acceder a FastAPI desde dentro o fuera del cluster
apiVersion: v1
kind: Service
metadata:
  name: inventary-service
spec:
  selector:
    app: inventary
  ports:
    - name: rest
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
