apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  selector:
    app: inventory
  ports:
    # Puerto REST
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    # Puerto gRPC
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  type: ClusterIP
