apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    # Puerto REST
    - name: http
      port: 5000
      targetPort: 5000
    # Puerto gRPC
    - name: grpc
      port: 50053
      targetPort: 50053
  type: ClusterIP
