apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    # Puerto REST
    - name: http
      port: 7000
      targetPort: 7000
      protocol: TCP
    # Puerto gRPC
    - name: grpc
      port: 50052
      targetPort: 50052
      protocol: TCP
  type: ClusterIP
