apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: tomas/user-service:latest
          ports:
            - containerPort: 6000
          env:
            - name: PORT
              value: "6000"
            - name: MONGO_URI
              value: "mongodb+srv://Jcarvajal0810:Nutella_0810@sharedm0.d3q2w0n.mongodb.net/userdb?retryWrites=true&w=majority&appName=SharedM0"
            - name: JWT_SECRET
              value: "WNXRO/cJDB5vORlhPq0098HAlggUdTu/Tk+E7Aqsd54="
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 6000
      targetPort: 6000
  type: ClusterIP
