# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckStock = channel.unary_unary(
                '/inventory.InventoryService/CheckStock',
                request_serializer=inventory__pb2.StockRequest.SerializeToString,
                response_deserializer=inventory__pb2.StockResponse.FromString,
                _registered_method=True)
        self.ReserveStock = channel.unary_unary(
                '/inventory.InventoryService/ReserveStock',
                request_serializer=inventory__pb2.ReserveRequest.SerializeToString,
                response_deserializer=inventory__pb2.ReserveResponse.FromString,
                _registered_method=True)
        self.ConfirmStockReduction = channel.unary_unary(
                '/inventory.InventoryService/ConfirmStockReduction',
                request_serializer=inventory__pb2.ConfirmRequest.SerializeToString,
                response_deserializer=inventory__pb2.ConfirmResponse.FromString,
                _registered_method=True)
        self.ReleaseStock = channel.unary_unary(
                '/inventory.InventoryService/ReleaseStock',
                request_serializer=inventory__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=inventory__pb2.ReleaseResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmStockReduction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseStock(self, request, context):
        """🆕 NUEVO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=inventory__pb2.StockRequest.FromString,
                    response_serializer=inventory__pb2.StockResponse.SerializeToString,
            ),
            'ReserveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStock,
                    request_deserializer=inventory__pb2.ReserveRequest.FromString,
                    response_serializer=inventory__pb2.ReserveResponse.SerializeToString,
            ),
            'ConfirmStockReduction': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmStockReduction,
                    request_deserializer=inventory__pb2.ConfirmRequest.FromString,
                    response_serializer=inventory__pb2.ConfirmResponse.SerializeToString,
            ),
            'ReleaseStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseStock,
                    request_deserializer=inventory__pb2.ReleaseRequest.FromString,
                    response_serializer=inventory__pb2.ReleaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/CheckStock',
            inventory__pb2.StockRequest.SerializeToString,
            inventory__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ReserveStock',
            inventory__pb2.ReserveRequest.SerializeToString,
            inventory__pb2.ReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmStockReduction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ConfirmStockReduction',
            inventory__pb2.ConfirmRequest.SerializeToString,
            inventory__pb2.ConfirmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ReleaseStock',
            inventory__pb2.ReleaseRequest.SerializeToString,
            inventory__pb2.ReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
