# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\x1f\n\x0cStockRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\"K\n\rStockResponse\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\x17\n\x0f\x61vailable_units\x18\x02 \x01(\x05\x12\x10\n\x08in_stock\x18\x03 \x01(\x08\"3\n\x0eReserveRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"3\n\x0fReserveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0e\x43onfirmRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"5\n\x0f\x43onfirmResponse\x12\x11\n\tconfirmed\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0eReleaseRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"3\n\x0fReleaseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb1\x02\n\x10InventoryService\x12?\n\nCheckStock\x12\x17.inventory.StockRequest\x1a\x18.inventory.StockResponse\x12\x45\n\x0cReserveStock\x12\x19.inventory.ReserveRequest\x1a\x1a.inventory.ReserveResponse\x12N\n\x15\x43onfirmStockReduction\x12\x19.inventory.ConfirmRequest\x1a\x1a.inventory.ConfirmResponse\x12\x45\n\x0cReleaseStock\x12\x19.inventory.ReleaseRequest\x1a\x1a.inventory.ReleaseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=30
  _globals['_STOCKREQUEST']._serialized_end=61
  _globals['_STOCKRESPONSE']._serialized_start=63
  _globals['_STOCKRESPONSE']._serialized_end=138
  _globals['_RESERVEREQUEST']._serialized_start=140
  _globals['_RESERVEREQUEST']._serialized_end=191
  _globals['_RESERVERESPONSE']._serialized_start=193
  _globals['_RESERVERESPONSE']._serialized_end=244
  _globals['_CONFIRMREQUEST']._serialized_start=246
  _globals['_CONFIRMREQUEST']._serialized_end=297
  _globals['_CONFIRMRESPONSE']._serialized_start=299
  _globals['_CONFIRMRESPONSE']._serialized_end=352
  _globals['_RELEASEREQUEST']._serialized_start=354
  _globals['_RELEASEREQUEST']._serialized_end=405
  _globals['_RELEASERESPONSE']._serialized_start=407
  _globals['_RELEASERESPONSE']._serialized_end=458
  _globals['_INVENTORYSERVICE']._serialized_start=461
  _globals['_INVENTORYSERVICE']._serialized_end=766
# @@protoc_insertion_point(module_scope)
