# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inventory_pb2 as services_dot_inventory__pb2


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckStock = channel.unary_unary(
                '/inventory.InventoryService/CheckStock',
                request_serializer=services_dot_inventory__pb2.StockRequest.SerializeToString,
                response_deserializer=services_dot_inventory__pb2.StockResponse.FromString,
                )
        self.ReserveStock = channel.unary_unary(
                '/inventory.InventoryService/ReserveStock',
                request_serializer=services_dot_inventory__pb2.ReserveRequest.SerializeToString,
                response_deserializer=services_dot_inventory__pb2.ReserveResponse.FromString,
                )
        self.ConfirmStockReduction = channel.unary_unary(
                '/inventory.InventoryService/ConfirmStockReduction',
                request_serializer=services_dot_inventory__pb2.ConfirmRequest.SerializeToString,
                response_deserializer=services_dot_inventory__pb2.ConfirmResponse.FromString,
                )


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmStockReduction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=services_dot_inventory__pb2.StockRequest.FromString,
                    response_serializer=services_dot_inventory__pb2.StockResponse.SerializeToString,
            ),
            'ReserveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStock,
                    request_deserializer=services_dot_inventory__pb2.ReserveRequest.FromString,
                    response_serializer=services_dot_inventory__pb2.ReserveResponse.SerializeToString,
            ),
            'ConfirmStockReduction': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmStockReduction,
                    request_deserializer=services_dot_inventory__pb2.ConfirmRequest.FromString,
                    response_serializer=services_dot_inventory__pb2.ConfirmResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/CheckStock',
            services_dot_inventory__pb2.StockRequest.SerializeToString,
            services_dot_inventory__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReserveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/ReserveStock',
            services_dot_inventory__pb2.ReserveRequest.SerializeToString,
            services_dot_inventory__pb2.ReserveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmStockReduction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/ConfirmStockReduction',
            services_dot_inventory__pb2.ConfirmRequest.SerializeToString,
            services_dot_inventory__pb2.ConfirmResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
